### ISSUE TITLE
Prune hardware

### ISSUE THREAD

**Issue by athajaerel** [FatmanUK/k3s_playground#124] opened 2024-02-28 11:30 UTC
Get rid of unneeded things like mice and trackpads, etc.

**Comment by athajaerel** [comment] 2024-03-01 09:43
Nothing really unneeded and removable at home site.

**Comment by athajaerel** [comment] 2024-03-01 09:43
Gang site has no VMs, so site:work label applied.

**Comment by FatmanUK** [comment] 2024-03-18 21:43
Dupe of #251 .

**Closed as not planned by FatmanUK** 2024-03-18 21:43 UTC
Labels: enhancement, site:work, why:stability
